### ISSUE TITLE
Linking CXX shared library ../../bin/libcal3d.so

### ISSUE THREAD

**Issue by sirus20x6** [mp3butcher/Cal3D#4]
after mkdir built && cd built
cmake ..
I run make
user@nid:~/git/Cal3D/cal3d/built$ make
Linking CXX shared library ../../bin/libcal3d.so
c++: error: SONAME_FLAGlibcal3d.so: No such file or directory
make[2]: *** [../bin/libcal3d.so] Error 1
make[1]: *** [src/CMakeFiles/cal3d.dir/all] Error 2
make: *** [all] Error 2

ubuntu 12. I had to compile a new version of cmake and compile and install glew. This is for an embedded system I can't just upgrade everything btw.

**Comment by mp3butcher** [comment]
please give more details about cmake version and  compiler used
purge cmakecache and try to diagnose with 
`VERBOSE=1 make`
I think the bug is on your side
