### ISSUE TITLE
Mac OSX src/quaternion.cpp compile issue

### ISSUE THREAD

**Issue by hibba42** [mp3butcher/Cal3D#5]
Hi all!

I would appreciate any help in troubleshooting, please :-) So far I've successfully run the ./configure command which generated the Makefiles, but am getting the following errors when running make:

```
g++ -DHAVE_CONFIG_H -I. -I.. -I../cal3d/src  -I../src  -O2 -fno-rtti -MT quaternion.o -MD 
-MP -MF .deps/quaternion.Tpo -c -o quaternion.o quaternion.cpp

quaternion.cpp:31:2: error: unknown type name 'CalQuaternion'; did you mean
      'cal3d::CalQuaternion'?
        CalQuaternion q;
        ^~~~~~~~~~~~~
        cal3d::CalQuaternion

../src/cal3d/quaternion.h:26:18: note: 'cal3d::CalQuaternion' declared here
        class CAL3D_API `CalQuaternion` 
```

I'm a bit stuck, as the quaternion.cpp file has the line `using namespace cal3d;` and am a little unsure what the compiler thinks is missing.  

This is on Mac OS X 10.15.1, if that's any help.

Thank you in advance!

**Comment by mp3butcher** [comment]
use cmake

**Comment by mp3butcher** [comment]
I've never test cmake configuration on mac but it should works
