### ISSUE TITLE
Convert cal3d

### ISSUE THREAD

**Issue by BHare1985** [mp3butcher/Cal3D#6]
Is there any software that can convert cal3d files to some type of modem format like FBX or OBJ?

I tried using milkshape but it just freezes when I load a crf

**Comment by mp3butcher** [comment]
https://github.com/mp3butcher/Cal3D/tree/master/cal3d/plugins/cal3d_maya_exporter and https://github.com/mp3butcher/Cal3D/tree/master/cal3d/plugins/cal3d_max_exporter need maintenance.
You'd need old versions in order plugin outputs to be read.

**Comment by BHare1985** [comment]
These are for exporting from maya/3ds into cal3d. I am interested in importing ( I have cal3d files, I want to convert to something else). It looks like https://github.com/mp3butcher/Cal3D/tree/master/cal3d/plugins/cal3d_max_importer may be what I need
