### ISSUE TITLE
fileformats.txt.in XMF file and CMF file format are not matching

### ISSUE THREAD

**Issue by swanandb2** [mp3butcher/Cal3D#7]
I was trying to load CMF file and convert it to readable XML struct.
I am stuck at Morph file line no 271. Can you please help us to understand how we can get Number of blendvert?

[first morph]  
     **len morph name     4   integer** [Length is specified in CMF]
    morph name             var     string  
    **num blendvert          4       integer**   This parameter I was not able to locate?
      [blendvertex]
        **vertex id              4       integer   index to original vertex** As per my finding after name string, next 4 bytes correspond to tis entry.
        position x             4       float     morph position in model space
        position y             4       float
        position z             4       float
        normal x               4       float     morph normal in model space
        normal y               4       float
        normal z               4       float
        [for all map]
            u coordinate         4       float     map coordinates
            v coordinate         4       float
        [end for all map]
    [all other blendvertices]

Thanks,
SB

**Comment by mp3butcher** [comment]
Sorry for my late answer.
num blendvert is the number of vertices of the original mesh

**Comment by swanandb2** [comment]
Sadly it's not working... I guess same ☹️

**Comment by swanandb2** [comment]
Actually I did try to build code in vs2017 but it's difficult ... To port I
also hered that there are issues in stl, so thinking to create parser in
c#...But my logic fails

May be imvu use different file specs

**Comment by mp3butcher** [comment]
yes imvu is not cal3D
