### ISSUE TITLE
Character animation without bones 

### ISSUE THREAD

**Issue by elkhalafy** [mp3butcher/Cal3D#9]
How are you? 

I found Idea for character animation without rigging or bones. This idea created by pixar studios called character articulation through profile curves or Curvenent
They have been released the paper about this idea. So please if you able to do this As standalone Free application for Windows OS. It will be great

Look at the video and download the paper too

https://youtu.be/gUJ4RxMdVn8

Download the paper here :-

https://graphics.pixar.com/library/ProfileMover/paper.pdf

Please let me know, you will create it or not

Thank you

**Comment by elkhalafy** [comment]
Please answer

**Comment by mp3butcher** [comment]
Interesting reading however the approach is fitted for movies not for real time characters
cf table 1: Panda sample takes 149.1+97.8+9.7= 256 ms to update

**Comment by elkhalafy** [comment]
It works for everything!!, Movies and real time characters, as i l see you don't need to create it Right?
